### ISSUE TITLE
Snippet design enhancements

### ISSUE THREAD

**Issue by buddh4** [humhub-contrib/newmembers#4]
Title and spacing looks a bit broken:

![grafik](https://user-images.githubusercontent.com/9800854/66824976-a025e580-ef49-11e9-8b9d-145ef1f7ddb9.png)

**Comment by MasterMindNET** [comment]
Hi @buddh4,
What do  you mean by that? what should be fixed? 
As for me it looks not bad, let me know what I can do for this task.

**Comment by buddh4** [comment]
This was probably fixed in the core already.
